plugins:
  postcss-import: {}
  postcss-cssnext: {
    features: {
      customProperties: {
        warnings: false # turn on to see warnings about css variables
      }
    }
  }
  autoprefixer: {
    grid: true,
    flexbox: 'no-2009'
  }
